#!/bin/bash

#generated by chatgpt and changed to work
#launches the game and python script with autosave enables at the same time

set -x
#set path to your dominins location
DOM6_PATH="$HOME/.steam/debian-installation/steamapps/common/Dominions6/dom6.sh"
AUTOSAVE_PATH="$HOME/.dominions6/dom6_autosave.py"
PIPE="/tmp/dom6_pipe"

# Create named pipe if it doesn't exist
[ ! -p "$PIPE" ] && mkfifo "$PIPE"

# Start Python script in background, reading from the pipe
python3 -u "$AUTOSAVE_PATH" < "$PIPE" &
PYTHON_PID=$!


# Open pipe for writing and keep it open (file descriptor 3)
exec 3> "$PIPE"


# Send initial input "3" without blocking
echo "3" > "$PIPE" &

# Start Dominions 6 in foreground
"$DOM6_PATH"

# Game exited → send "4" to Python
echo "4" > "$PIPE" &

# Wait for Python to finish
wait $PYTHON_PID

# Clean up
rm "$PIPE"
